groups:
  vault:
    env:
      VENV_DIR: venv
      HOSTS_DIR: ansible/config/hosts
      TASKS_DIR: ansible/roles/maps-upload/tasks
      ROLES_DIR: ansible/roles
      VAULT_CONFIG: ansible/config/vault-config.yaml
    tasks:
      create-vault-config:
        help: Create the vault configuration file
        run: |
          ansible-vault create "${{ env.VAULT_CONFIG }}"

      change-vault-config:
        help: Edit the vault configuration file
        run: |
          ansible-vault edit "${{ env.VAULT_CONFIG }}"

      change-vault-passwd:
        help: Change the password of the vault configuration file
        run: |
          ansible-vault rekey "${{ env.VAULT_CONFIG }}"

  ansible:
    env:
      VENV_DIR: venv
      HOSTS_DIR: ansible/config/hosts
      TASKS_DIR: ansible/roles/maps-upload/tasks
      ROLES_DIR: ansible/roles
      VAULT_CONFIG: ansible/config/vault-config.yaml
    tasks:
      containers-system-update:
        help: Run ansible scripts for containers system update (prod only)
        run: |
          ansible-playbook -i "${{ env.HOSTS_DIR }}" --ask-vault-pass \
            --extra-vars "@${{ env.VAULT_CONFIG }}" \
            playbooks/containers-system-update.yaml \
            --skip-tags staging \
            --verbose

      update-alertas:
        help: Execute the playbook to update alerts
        args:
          disease:
            help: Specify the disease name (e.g., 'dengue', 'chik', 'zika')
            type: string
            required: true
          yearweek:
            help: Specify the yearweek from epiweek as YYYYWW (e.g., 202545)
            type: string
            required: true
        run: |
          ansible-playbook -i "${{ env.HOSTS_DIR }}" --ask-vault-pass \
            --extra-vars "@${{ env.VAULT_CONFIG }}" \
            -e "yearweek=${{ args.yearweek }} disease=${{ args.disease }}" \
            playbooks/historico-alert-prepare-hosts.yaml --verbose

      sync-maps:
        help: Execute the playbook for incidence map upload
        run: |
          ansible-playbook -i "${{ env.HOSTS_DIR }}" --ask-vault-pass \
            --extra-vars "@${{ env.VAULT_CONFIG }}" \
            playbooks/incidence-map-upload.yaml --verbose

      upload-sinan-dbf:
        help: Execute the playbook for uploading SINAN DBFs
        args:
          file-path:
            help: Absolute file path to be exported
            type: string
            required: true
          year:
            help: Notification year (format YYYY)
            type: string
            required: true
          codarea:
            help: Specify area code (default 'BR')
            type: string
            required: false
            default: "BR"
          disease:
            help: Specify the disease (default 'DEN')
            type: string
            required: false
            default: "DEN"
        run: |
          bash -lc '
            FILE="${{ args.file_path }}"
            FILE="${FILE%/}"
            FILE_SUFFIX="${FILE##*.}"

            EXPORT_DATE=$(date +"%m-%d-%Y")
            DISEASE_UPPER=$(echo "${{ args.disease }}" | tr "[:lower:]" "[:upper:]")
            CODE_AREA_UPPER=$(echo "${{ args.codarea }}" | tr "[:lower:]" "[:upper:]")

            case "$DISEASE_UPPER" in
              CHIK) CID="A92.0" ;;
              ZIKA) CID="A928" ;;
              *)    CID="A90" ;;
            esac

            ansible-playbook -i "${{ env.HOSTS_DIR }}" --ask-vault-pass \
              --extra-vars "@${{ env.VAULT_CONFIG }}" \
              -e "file_path=${{ args.file_path }} \
                  code_area=${CODE_AREA_UPPER} \
                  disease=${DISEASE_UPPER} \
                  notif_year=${{ args.year }} \
                  export_date=${EXPORT_DATE} \
                  file_type=${FILE_SUFFIX} \
                  cid=${CID}" \
              playbooks/upload-sinan-dbf.yaml --verbose
          '

      history:
        help: View a specific remote log file under /var/log/ansible/
        args:
          logfile:
            help: Log file name (e.g., system_update_staging.log)
            type: string
            required: true
        run: |
          ansible -i "${{ env.HOSTS_DIR }}" --ask-vault-pass \
            --extra-vars "@${{ env.VAULT_CONFIG }}" \
            -m command -a "cat /var/log/ansible/${{ args.logfile }}" all --verbose
