---
- name: Synchronize Map Images Directory and Execute Script
  hosts: cluster
  gather_facts: true

  vars:
    ROLE_MAPS_DIR: ../ansible/roles/maps-upload
    HOST_SOURCE_DIR: '{{ ROLE_MAPS_DIR }}/images/incidence_maps/'
    REMOTE_TARGET_DIR: /Storage/infodengue_data/img/incidence_maps
    LOG_PATH: /var/log/ansible

  tasks:
    - name: Synchronize Map Images Directory
      synchronize:
        src: "{{ HOST_SOURCE_DIR }}"
        dest: "{{ REMOTE_TARGET_DIR }}"
      delegate_to: localhost

    - name: Clean up bash scripts from remote and destination directories
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ HOST_SOURCE_DIR }}/*.sql"
      delegate_to: localhost
 
    - name: Register sent images in the log file
      shell: echo "{{ lookup('pipe','date') }} ==> Synchronize Map Images Successfully" >> {{ LOG_PATH }}/incidence_maps_update.log 2>&1

- name: Include containers-system-update playbook to update and reload all system
  ansible.builtin.import_playbook: containers-system-update.yaml
