---
- name: Synchronize Map Images Directory and Execute Script
  hosts: cluster
  gather_facts: true

  vars:
    ROLE_MAPS_DIR: ../ansible/roles/maps-upload
    SRC_DIR: '{{ ROLE_MAPS_DIR }}/images/incidence_maps/'
    DEST_DIR: /Storage/staging_data/img/incidence_maps
    LOG_PATH: /var/log/ansible

  tasks:
    - name: Synchronize Map Images Directory
      synchronize:
        src: "{{ SRC_DIR }}"
        dest: "{{ DEST_DIR }}"
      delegate_to: localhost

    - name: Register sent images in the log file
      shell: echo "{{ lookup('pipe','date') }} ==> Synchronize Map Images Successfully" >> {{ LOG_PATH }}/incidence_maps_update.log 2>&1

