- name: Synchronize Map Images Directory and Execute Script
  hosts: cluster
  gather_facts: true

  vars:
    SCRIPT_NAME: sync_maps_from_static.sh
    SCRIPT_DIR: /opt/services/AlertaDengue
    LOG_PATH: /var/log/ansible
    SRC_DIR: sync_maps/incidence_maps/
    DEST_DIR: /Storage/infodengue_data/img/incidence_maps/

  tasks:
    - name: Synchronize Map Images Directory
      synchronize:
        src: "{{ SRC_DIR }}"
        dest: "{{ DEST_DIR }}"
      delegate_to: localhost

    - name: Execute Script on Server
      become: true
      become_user: administrador
      shell: "nohup ./{{ SCRIPT_NAME }} > {{ LOG_PATH }}/system_update_epiweeks.log 2>&1 &"
      args:
        chdir: "{{ SCRIPT_DIR }}"
