-- CREATE ROLE "Dengue";
-- ALTER ROLE "Dengue" WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION NOBYPASSRLS VALID UNTIL 'infinity';
SELECT nspname FROM pg_catalog.pg_namespace;
